package org.raul.javawebscarper.scraper.adapter.instagram;

public enum InstagramAuthenticationStatus {
	AUTHENTICATED,
	AUTH_REQUIRED,
	AUTH_STATE_MISSING,
	AUTH_STATE_EXPIRED,
	CHALLENGE_REQUIRED,
	TWO_FACTOR_REQUIRED,
	SUSPICIOUS_LOGIN,
	CONSENT_REQUIRED,
	RATE_LIMITED,
	ACCOUNT_RESTRICTED,
	TEMPORARILY_BLOCKED,
	UNKNOWN
}
