package org.raul.javawebscarper.scraper.adapter.facebook;

public enum FacebookAuthenticationStatus {
	AUTHENTICATED,
	AUTH_REQUIRED,
	AUTH_STATE_MISSING,
	AUTH_STATE_EXPIRED,
	CHECKPOINT_REQUIRED,
	CHALLENGE_REQUIRED,
	TWO_FACTOR_REQUIRED,
	RATE_LIMITED,
	ACCOUNT_RESTRICTED,
	TEMPORARILY_BLOCKED,
	UNKNOWN
}
