package org.raul.javawebscarper.scraper.adapter.tiktok;

public enum TikTokAuthenticationStatus {
	AUTHENTICATED,
	ANONYMOUS_ACCESS,
	AUTH_REQUIRED,
	AUTH_STATE_MISSING,
	AUTH_STATE_EXPIRED,
	LOGIN_MODAL_BLOCKING,
	CAPTCHA_REQUIRED,
	VERIFICATION_REQUIRED,
	TWO_FACTOR_REQUIRED,
	RATE_LIMITED,
	TEMPORARILY_BLOCKED,
	ACCOUNT_RESTRICTED,
	CONSENT_REQUIRED,
	UNKNOWN
}
